language: ruby
sudo: false
rvm: 2.4.2
env:
  global:
  - CHIRP_SUMMARY_OUTPUT="${TRAVIS_BUILD_DIR}/chirp.json"
  - CHIRP_TRACKER_STATS_URL="https://chirp-tracker-staging.herokuapp.com/stats"
  - SITE=org
addons: { apt: { packages: [bc] } }
linux_shared: &linux_shared
  os: linux
  addons: { apt: { packages: [bc] } }
matrix:
  include:
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: precise
    env: QUEUE=gce DIST=precise
    <<: *linux_shared
  - sudo: false
    dist: trusty
    env: QUEUE=ec2 DIST=trusty
    <<: *linux_shared
  - group: packet-test
    dist: trusty
    env: QUEUE=packet DIST=trusty
    <<: *linux_shared
  - os: osx
    rvm: default
    env: QUEUE=macstadium6 IMAGE=default
  - os: osx
    osx_image: xcode8
    rvm: default
    env: QUEUE=macstadium6 IMAGE=xcode8
script: bundle exec chirp scripts
after_script: bundle exec chirp sendstats 2>/dev/null
after_failure: bundle exec chirp dumplogs
notifications:
  webhooks:
    urls:
    - 'https://chirp-tracker-production.herokuapp.com/travis'
    on_success: always
    on_failure: never
